# Linear Regression

In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [8]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))

In [9]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [10]:
y=np.array([5,20,14,32,22,38])

In [11]:
y

array([ 5, 20, 14, 32, 22, 38])

In [12]:
#create a model and fit
model=LinearRegression()
model.fit(x,y)
model=LinearRegression().fit(x,y)

In [13]:
r_sq=model.score(x,y)
print(f"coefficient of determination:{r_sq}")
print(f"intercept:{model.intercept_}")
print(f"scope:{model.coef_}")

coefficient of determination:0.7158756137479542
intercept:5.633333333333329
scope:[0.54]


In [18]:
#predict result
y_pred=model.predict(x)
print(f"predicted response:/n{y_pred}")

predicted response:/n[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [14]:
y_pred=model.intercept_+model.coef_*x
print(f"predicted response:/n{y_pred}")

predicted response:/n[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [15]:
#Testing with new x and y
x_new=np.arange(5).reshape((-1,1))
y_new=model.predict(x_new)

In [16]:
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [17]:
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])