# Numpy

In [3]:
import numpy as np
array1=np.array([10,20,30,40,50])
array2=np.arange(5)
array2

array([0, 1, 2, 3, 4])

In [4]:
array3=array1+array2
array3

array([10, 21, 32, 43, 54])

In [5]:
array4=np.array([1,2,3,4])
array4

array([1, 2, 3, 4])

In [6]:
array1*2

array([ 20,  40,  60,  80, 100])

In [7]:
array1**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [8]:
array1[array1>=30]

array([30, 40, 50])

In [11]:
import numpy as np
A=np.array([[3,2],[0,1]])
B=np.array([[3,1],[2,1]])
print(A)

[[3 2]
 [0 1]]


In [12]:
print(B)

[[3 1]
 [2 1]]


In [13]:
print(A+B)

[[6 3]
 [2 2]]


In [15]:
A.dot(B)

array([[13,  5],
       [ 2,  1]])

In [16]:
array=np.random.random((2,2))
array

array([[0.97563519, 0.63196601],
       [0.10410567, 0.64329429]])

In [17]:
array.sum()

2.3550011644402145

In [18]:
array.min()

0.10410567243791702

In [19]:
array.sum(axis=0)

array([1.07974086, 1.2752603 ])

In [20]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
b=np.array([2,4,6])
np.add(a,b)

array([[ 2,  5,  8],
       [ 5,  8, 11],
       [ 8, 11, 14]])

In [22]:
a3=np.arange(9)
print(a3)

[0 1 2 3 4 5 6 7 8]


In [24]:
print(a3.reshape(3,3))
print(a3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [25]:
print(a3.resize(3,3))
print(a3)

None
[[0 1 2]
 [3 4 5]
 [6 7 8]]
